create table EMPLOYEE (
  ID bigint generated by default as identity,
  KVKNUMMER varchar(8) not null,
  OPGAVE_ID varchar(255) not null,
  DOELSYSTEEM varchar(128) not null,
  STATUS varchar(128) not null,
  STATUS_MELDING varchar(2048),
  TIJDSTIP_AANGEMAAKT timestamp not null,

)