create table EMPLOYEE (
  ID bigint generated by default as identity,
  EMPLOYEE_NUMBER int not null,
  SOCIAL_SECURITY_NUMBER int not null,
  NAME varchar(128) not null,
  EMPLOYED_DATE date not null,
  ACTION varchar(255),
  TIMESTAMP bigint,
  USER_PROFILE varchar(255)
)

create table ADDRESS (
  ID bigint generated by default as identity,
  STREET varchar(128) not null,
  HOUSE_NUMBER int not null,
  HOUSE_NUMBER_SUFFIX varchar(50) not null,
  POSTAL_CODE varchar(50) not null,
  CITY varchar(128) not null,
  ACTION varchar(255),
  TIMESTAMP bigint,
  USER_PROFILE varchar(255)
)

alter table Employee add constraint UK_Employee_1 unique (ADDRESS_ID)
alter table Employee add constraint UK_Employee_2 unique (EMPLOYEE_NUMBER)
alter table Employee add constraint FK_Employee_1 foreign key (ADDRESS_ID) references Address